POST HTTP://localhost:3000/login
Content-Type: application/json

{
  "email" : "saul@gmail.com",
  "senha": "123456"
}

###

DELETE HTTP://localhost:3000/logout
Authorization: 561eaf9637592367a7a97d95b79d6c5f

###

GET HTTP://localhost:3000/usuarios/1
Authorization: cb5cf06269263cd2b36d201396bfc67f



